// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltwsysdpkzbdywtedwdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0d3N5c2Rwa3piZHl3dGVkd2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3OTE2MDgsImV4cCI6MjA1ODM2NzYwOH0.xOhoazqxWjuJho6L4t38gt9jeHxx_W9P30ivn2IbDjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);